configserver:
  image: idugalic/configserver
  ports:
   - "8888:8888"
  restart: always
registry:
  image: idugalic/registry
  ports:
   - "8761:8761"
  links:
   - configserver
  environment:
    HOST_IP: $DOCKER_HOST_IP
  restart: always
authserver:
  image: idugalic/authserver
  ports:
   - "9999:9999"
  links:
   - configserver
  restart: always
adminserver:
  image: idugalic/adminserver
  ports:
   - "9998:9998"
  links:
   - configserver
   - registry
  restart: always
circuit-breaker:
  image: idugalic/circuit-breaker 
  ports:
   - "6161:6161"
  links:
   - registry
   - configserver
  restart: always
query-side-blog:
  image: idugalic/query-side-blog 
  ports:
   - "8081:8081"
  links:
   - registry
   - configserver
   - my-mongo
   - my-rabbit
   - authserver
  restart: always
command-side-blog:
  image: idugalic/command-side-blog 
  ports:
   - "8080:8080"
  links:
   - registry
   - configserver
   - my-mongo
   - my-rabbit
   - authserver
  restart: always
query-side-project:
  image: idugalic/query-side-project 
  ports:
   - "8083:8083"
  links:
   - registry
   - configserver
   - my-mongo
   - my-rabbit
   - authserver
  restart: always
command-side-project:
  image: idugalic/command-side-project 
  ports:
   - "8082:8082"
  links:
   - registry
   - configserver
   - my-mongo
   - my-rabbit
   - authserver
  restart: always
api-gateway:
  image: idugalic/api-gateway 
  ports:
   - "9000:9000"
  links:
   - registry
   - configserver
   - authserver
   - my-mongo
   - my-rabbit
  restart: always
my-mongo:
  image: mongo:3.0.4
  hostname: mongodb
  command: mongod --smallfiles
  ports:
    - "27017:27017"
  restart: always
    
my-rabbit:
  image: rabbitmq:3-management
  hostname: rabbitmq
  ports:
    - "5672:5672"
    - "15672:15672"
  environment:
    RABBITMQ_DEFAULT_USER: test
    RABBITMQ_DEFAULT_PASS: password
    RABBITMQ_NODENAME: my-rabbit
  restart: always