version: "2"

services:
  configserver:
    image: idugalic/configserver
    ports:
     - "8888:8888"
  registry:
    image: idugalic/registry
    ports:
     - "8761:8761"
    environment:
      HOST_IP: $DOCKER_HOST_IP
  authserver:
    image: idugalic/authserver
    ports:
     - "9999:9999"
  adminserver:
    image: idugalic/adminserver
    ports:
     - "9998:9998"
  circuit-breaker:
    image: idugalic/circuit-breaker 
    ports:
     - "6161:6161"
  query-side-blog:
    image: idugalic/query-side-blog 
    ports:
     - "8081:8081"
  command-side-blog:
    image: idugalic/command-side-blog 
    ports:
     - "8080:8080"
  query-side-project:
    image: idugalic/query-side-project 
    ports:
     - "8083:8083"
  command-side-project:
    image: idugalic/command-side-project 
    ports:
     - "8082:8082"
  api-gateway:
    image: idugalic/api-gateway 
    ports:
     - "9000:9000"
  my-mongo:
    image: mongo:3.0.4
    hostname: mongodb
    command: mongod --smallfiles
    ports:
      - "27017:27017"
    
  my-rabbit:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: test
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_NODENAME: my-rabbit
 